imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines:     ['twig']
    default_locale:  %locale%
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - "ServerGroveLiveChatBundle:Form:fields.html.twig"

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar


# Doctrine Configuration
# doctrine:
#     dbal:
#         driver:   %database_driver%
#         host:     %database_host%
#         port:     %database_port%
#         dbname:   %database_name%
#         user:     %database_user%
#         password: %database_password%
#         charset:  UTF8
doctrine_mongodb:
  connections:
    default:
      server: mongodb://localhost:27017
      options:
        connect: true
  default_database: livechat
  auto_generate_hydrator_classes: true
  auto_generate_proxy_classes: true
  document_managers:
    default:
      mappings:
        ServerGroveLiveChatBundle: ~
      metadata_cache_driver: array # array, apc, xcache, memcache

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool: { type: memory }

server_grove_live_chat:
  cache_engine: mongo