security:
    encoders:
        ServerGrove\LiveChatBundle\Document\Operator: sha512

    role_hierarchy:
        ROLE_OPERATOR:    ROLE_USER
        ROLE_ADMIN:       ROLE_OPERATOR
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        default_provider:
            mongodb: { class: ServerGrove\LiveChatBundle\Document\Operator, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/sglivechat/admin/login$
            security: false

        secured_area:
            pattern:   ^/
            form_login:
                require_previous_session: false
                default_target_path: /sglivechat/admin
                login_path:          /sglivechat/admin/login
                check_path:          /sglivechat/admin/login-check
                username_parameter: login[email]
                password_parameter: login[passwd]
                csrf_parameter:     login[_token]
            logout:
                path:   /sglivechat/admin/logout
                target: /sglivechat/admin/login

    access_control:
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/sglivechat/admin/, roles: ROLE_ADMIN }
        - { path: ^/sglivechat/admin$, roles: ROLE_USER }